### ISSUE TITLE
关于准确率与精确率

### ISSUE THREAD

**Issue by Gray-ly** [ytzfhqs/AAAMLP-CN#11]
评估指标这一章中AccuracyScore=(TP+TN)/(TP+TN+FP+FN)的公式应该说的是准确率
![微信图片_20240307170933](https://github.com/ytzfhqs/AAAMLP-CN/assets/62938107/076799cb-5b06-4154-8029-640736a3ff1c)

**Comment by VEmpYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近有事，几天后回复。请原谅。

**Comment by Nagi-ovo** [comment]
> 评估指标这一章中AccuracyScore=(TP+TN)/(TP+TN+FP+FN)的公式应该说的是准确率 ![微信图片_20240307170933](https://private-user-images.githubusercontent.com/62938107/310817309-076799cb-5b06-4154-8029-640736a3ff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzY3NDksIm5iZiI6MTcwOTg3NjQ0OSwicGF0aCI6Ii82MjkzODEwNy8zMTA4MTczMDktMDc2Nzk5Y2ItNWIwNi00MTU0LTgwMjktNjQwNzM2YTNmZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA1NDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NWZhNmE2ZmZiMjgwMzQ2ZGM3ZWYzNjRhMWI0YjFlOTIzNDg1MDU2M2Y1NDZlYWUzY2M5OTkyZTAxZWQzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9y4_H90n7tCzQfi8s7WRTyIG42cs7ucDezCvV5aCLI)

Thanks!
