### ISSUE TITLE
issues in评估指标

### ISSUE THREAD

**Issue by LionKk99** [ytzfhqs/AAAMLP-CN#13]
<img width="984" alt="1709896820005" src="https://github.com/ytzfhqs/AAAMLP-CN/assets/128462443/698ab6f3-cdc0-4262-936a-63a81422245b">

在此处上面对于公式的描述不应该是“精确率”而应该是“准确率”

**Comment by MovisLi** [comment]
Merge this issue to #11 ,you can review [here](https://github.com/ytzfhqs/AAAMLP-CN/issues/11)

**Comment by Nagi-ovo** [comment]
Thanks for reporting!

**Comment by LionKk99** [comment]
> Merge this issue to #11, you can review it here. (https://github.com/ytzfhqs/AAAMLP-CN/issues/11)

Thank you！
