### ISSUE TITLE
invalid pdf

### ISSUE THREAD

**Issue by huangzsdy** [ytzfhqs/AAAMLP-CN#14]
![image](https://github.com/ytzfhqs/AAAMLP-CN/assets/17697681/3d6c97b2-91ad-4693-bbf0-96b0028df878)
This page opens with a prompt, "invalid pdf"

**Comment by VEmpYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近有事，几天后回复。请原谅。

**Comment by ytzfhqs** [comment]
@huangzsdy PDF now temporarily does not support the preview in Github, please clone the project to open locally, or use the [online reading](https://ytzfhqs.github.io/AAAMLP-CN/) sites
