### ISSUE TITLE
感谢汉化！

### ISSUE THREAD

**Issue by Nagi-ovo** [ytzfhqs/AAAMLP-CN#2]
此外，不知道你觉得做一个在线阅读方式有没有必要

**Comment by ytzfhqs** [comment]
非常开心这个项目能帮助到你，我觉得你的建议非常好。我现在查一下如何构建在线文档，如果你愿意，我们也可以一起完成这个工作！

**Comment by Nagi-ovo** [comment]
可以呀，我之前用mkdocs做过在线文档，效果可以参考：https://open-bjut.github.io/CodeJourney/
或者用hugo什么的框架搭一个也行

**Comment by Nagi-ovo** [comment]
除此之外，我可以跟着学习进度把代码部分给上中文注释，你觉得有必要嘛

**Comment by Nagi-ovo** [comment]
<img width="353" alt="image" src="https://github.com/ytzfhqs/AAAMLP-CN/assets/101612750/e07147b7-5727-47e1-a600-06132aa66949">
<br />
你是用Mac编辑的吧很hh，可能得麻烦你在修改文件后重新生成pdf文件，否则Win用户需要把图片路径都修改了..
<img width="312" alt="image" src="https://github.com/ytzfhqs/AAAMLP-CN/assets/101612750/72e82683-78a9-4a34-9398-20ef8ec4204b">

**Comment by ytzfhqs** [comment]
> 可以呀，我之前用mkdocs做过在线文档，效果可以参考：https://open-bjut.github.io/CodeJourney/ 或者用hugo什么的框架搭一个也行

好的，晚点我研究一下

**Comment by ytzfhqs** [comment]
> 除此之外，我可以跟着学习进度把代码部分给上中文注释，你觉得有必要嘛

我在翻译的时候有考虑顺便把代码注释写了，但是因为整个工作只有我一个人，考虑到时间因素，就没有做，实际上应该还是要有的。再一方面，因为作者权威性的缘故，可能也不会有太多人关注这个项目，比如到现在也只有3个star，所以这个工作会做，但是可能会延后一段时间

**Comment by ytzfhqs** [comment]
> <img alt="image" width="353" src="https://user-images.githubusercontent.com/101612750/265570685-e07147b7-5727-47e1-a600-06132aa66949.png">
> 你是用Mac编辑的吧很hh，可能得麻烦你在修改文件后重新生成pdf文件，否则Win用户需要把图片路径都修改了.. <img alt="image" width="312" src="https://user-images.githubusercontent.com/101612750/265570872-72e82683-78a9-4a34-9398-20ef8ec4204b.png">

是的，我想构建线上文档可能会有助于缓解这个问题，如果后面有比较频繁的纠错，那就隔一段时间更新一次PDF，事实上如果不是做修改工作PDF也比markdown文档更稳定，且清晰

**Comment by Nagi-ovo** [comment]
<img width="935" alt="image" src="https://github.com/ytzfhqs/AAAMLP-CN/assets/101612750/aab9d5c7-03fb-482f-b95c-877e497a7b65">
现在的效果~

**Comment by ytzfhqs** [comment]
@Nagi-ovo 哇！我觉得你做的好漂亮！

**Comment by Nagi-ovo** [comment]
加个微信沟通一下如何，感觉效率高点，最近在读这本书想着顺便把你的汉化版做大一些hhSent from my HONOR phone-------- Original message --------From: QingSong Hao ***@***.***>Date: Tue, Sep 5, 2023, 8:55 PMTo: ytzfhqs/AAAMLP-CN ***@***.***>Cc: Jesse Zhang ***@***.***>, Mention ***@***.***>Subject: Re: [ytzfhqs/AAAMLP-CN] 感谢汉化！ (Issue #2)
@Nagi-ovo 哇！我觉得你做的好漂亮！

**Comment by ytzfhqs** [comment]
当然可以，我的微信号是ytzfhqs
