### ISSUE TITLE
感谢汉化+在线文档美化

### ISSUE THREAD

**Issue by wlin16** [ytzfhqs/AAAMLP-CN#3]
非常感谢两位的贡献！

线上文档真的看起来好棒！非常想学习一下制作方式。请问可以联系你们请教一下这个线上文档该怎么制作吗

**Comment by Nagi-ovo** [comment]
本项目在线文档所用的主题的[官网](https://squidfunk.github.io/mkdocs-material/getting-started/)

可以以本项目为例，`.github/workflows`是自动化更新并部署GitHub Pages用的，所有项目都用它就行。克隆本仓库并下载相关的包(见`requirements.txt`)后输入`mkdocs serve`即可本地浏览效果，再自己去改改一下`mkdocs.yml`就能明白了~

**Comment by wlin16** [comment]
感谢回答！我去试试！汉化工作辛苦了！加油！
