### ISSUE TITLE
图像和文本那两章最近有推进的计划吗？

### ISSUE THREAD

**Issue by Kyrie666** [ytzfhqs/AAAMLP-CN#5]
图像和文本那两章最近有推进的计划吗？如果可以，我愿意提供帮助

**Comment by ytzfhqs** [comment]
@Kyrie666 Thank you very much for your willingness to help, but I've finished translating the images and text chapters and will merge them into the mian branch in 2 days!

**Comment by ytzfhqs** [comment]
@Kyrie666 As of October 25, 2023, I have completed the translation of the entire book. Please check out the master branch and I will close this issue.
