### ISSUE TITLE
environment文件

### ISSUE THREAD

**Issue by wangbyh** [ytzfhqs/AAAMLP-CN#6]
你好，并未找到你的环境配置文件，感谢你给我一个清晰的路径，万分感谢

**Comment by Nagi-ovo** [comment]
> 你好，并未找到你的环境配置文件，感谢你给我一个清晰的路径，万分感谢

请见[原项目仓库](https://github.com/abhishekkrthakur/approachingalmost/blob/master/environment.yml)

**Comment by VEmpYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近有事，几天后回复。请原谅。
